In [4]:
# Min Max
from sklearn.preprocessing import MinMaxScaler

data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
scaler = MinMaxScaler((-1, 1))
scaler.fit(data)
print(scaler.data_max_)
print(scaler.transform(data))
print(scaler.transform([[20, 20]]))

[ 1. 18.]
[[-1.  -1. ]
 [-0.5 -0.5]
 [ 0.   0. ]
 [ 1.   1. ]]
[[20.    1.25]]


In [6]:
# MaxAbs

from sklearn.preprocessing import MaxAbsScaler
X = [[ 1., -1.,  2.],
     [ 2.,  0.,  0.],
     [ 0.,  1., -1.]]
transformer = MaxAbsScaler().fit(X)
print(transformer)
print(transformer.transform(X))

MaxAbsScaler(copy=True)
[[ 0.5 -1.   1. ]
 [ 1.   0.   0. ]
 [ 0.   1.  -0.5]]


In [14]:
# Standard Scaler
from sklearn.preprocessing import StandardScaler
data = [[0, 0], [0, 0], [1, 1], [1, 1], [5, 100], [500, 500], [1000000, 10000]]
scaler = StandardScaler()
print(scaler.fit(data))
print(scaler.mean_)
print(scaler.scale_)
print(scaler.transform(data))
print(scaler.transform([[2, 100]]))

StandardScaler(copy=True, with_mean=True, with_std=True)
[142929.57142857   1514.57142857]
[349897.57956655   3468.27490495]
[[-0.40848974 -0.43669302]
 [-0.40848974 -0.43669302]
 [-0.40848688 -0.43640469]
 [-0.40848688 -0.43640469]
 [-0.40847545 -0.40786024]
 [-0.40706075 -0.29252913]
 [ 2.44948945  2.44658477]]
[[-0.40848402 -0.40786024]]


In [22]:
# One-hot / Dummy
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')
X = [['Male', 1], ['Female', 3], ['Female', 2]]
print(enc.fit(X))
enc.transform(X).toarray()

OneHotEncoder(categorical_features=None, categories=None,
       dtype=<class 'numpy.float64'>, handle_unknown='ignore',
       n_values=None, sparse=True)


array([[0., 1., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0.]])